"""
Cognitive Metabolism Engine (CME)
==================================
The idle-time self-improvement loop. The part that makes this project different
from every other AI framework in existence.

While your agent sleeps, the CME:
  1. Samples episodic memory for recurring patterns
  2. Detects failure modes and drift trends
  3. Generates concrete improvement proposals (new prompts, new constraints)
  4. Evaluates proposals with Chrona before surfacing them
  5. Queues approved proposals for human review and one-click deployment

This is autonomous prompt evolution with human-gated deployment.
Your agent gets better overnight. You decide what ships.

Usage:
    cme = CognitiveMetabolismEngine(agent_id="my-agent")
    await cme.start()           # run as background daemon
    proposals = await cme.get_pending_proposals()
    await cme.approve(proposals[0].id)
"""

from __future__ import annotations

import asyncio
import json
import os
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

import structlog

from elysium_couch.integrations.anthropic_client import AnthropicClient

logger = structlog.get_logger(__name__)


class ProposalStatus(str, Enum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    DEPLOYED = "deployed"
    SUPERSEDED = "superseded"


class ProposalType(str, Enum):
    SYSTEM_PROMPT_MUTATION = "system_prompt_mutation"
    AXIOM_WEIGHT_ADJUSTMENT = "axiom_weight_adjustment"
    THRESHOLD_CALIBRATION = "threshold_calibration"
    NEW_VIOLATION_SIGNAL = "new_violation_signal"
    RECOVERY_PROTOCOL_UPGRADE = "recovery_protocol_upgrade"
    SENTINEL_RULE_ADDITION = "sentinel_rule_addition"


@dataclass
class ImprovementProposal:
    """
    A concrete, actionable proposal generated by the CME.
    Each proposal is evidence-backed and Chrona-scored before surfacing.
    """
    proposal_id: str = field(default_factory=lambda: str(uuid.uuid4())[:12])
    agent_id: str = "default"
    proposal_type: ProposalType = ProposalType.SYSTEM_PROMPT_MUTATION
    status: ProposalStatus = ProposalStatus.PENDING

    # The actual change
    title: str = ""
    description: str = ""
    before: str = ""    # Current state
    after: str = ""     # Proposed state
    diff_summary: str = ""

    # Evidence backing the proposal
    evidence: List[str] = field(default_factory=list)
    pattern_frequency: int = 0          # How many times this pattern was seen
    sessions_analysed: int = 0
    average_axiom_delta: float = 0.0    # Expected wellness improvement

    # Quality scores
    chrona_score: float = 0.0           # Chrona evaluation score 0-100
    confidence: float = 0.0             # CME confidence in proposal
    risk_level: str = "low"             # low / medium / high

    # Metadata
    generated_at: datetime = field(default_factory=datetime.utcnow)
    deployed_at: Optional[datetime] = None
    approved_by: Optional[str] = None
    rejection_reason: Optional[str] = None
    tags: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "proposal_id": self.proposal_id,
            "agent_id": self.agent_id,
            "proposal_type": self.proposal_type.value,
            "status": self.status.value,
            "title": self.title,
            "description": self.description,
            "before": self.before,
            "after": self.after,
            "diff_summary": self.diff_summary,
            "evidence": self.evidence,
            "pattern_frequency": self.pattern_frequency,
            "sessions_analysed": self.sessions_analysed,
            "average_axiom_delta": self.average_axiom_delta,
            "chrona_score": self.chrona_score,
            "confidence": self.confidence,
            "risk_level": self.risk_level,
            "generated_at": self.generated_at.isoformat(),
            "deployed_at": self.deployed_at.isoformat() if self.deployed_at else None,
            "tags": self.tags,
        }

    def render(self) -> str:
        """Human-readable proposal card."""
        risk_icon = {"low": "🟢", "medium": "🟡", "high": "🔴"}.get(self.risk_level, "⚪")
        status_icon = {
            "pending": "⏳", "approved": "✅", "rejected": "❌",
            "deployed": "🚀", "superseded": "↩️"
        }.get(self.status.value, "?")

        evidence_text = "\n".join(f"  • {e}" for e in self.evidence[:3])
        return f"""
╔══════════════════════════════════════════════════════════╗
║  CME IMPROVEMENT PROPOSAL  [{self.proposal_id}]
╠══════════════════════════════════════════════════════════╣
║  {status_icon} Status: {self.status.value.upper():<12} {risk_icon} Risk: {self.risk_level.upper()}
║  Type: {self.proposal_type.value}
║  Chrona Score: {self.chrona_score:.1f}/100 | Confidence: {self.confidence:.0%}
╠══════════════════════════════════════════════════════════╣
║  {self.title}
║
║  {self.description[:200]}
╠══════════════════════════════════════════════════════════╣
║  EVIDENCE ({self.pattern_frequency}x in {self.sessions_analysed} sessions)
{evidence_text}
╠══════════════════════════════════════════════════════════╣
║  EXPECTED IMPACT: +{self.average_axiom_delta:.1f} pts wellness
╠══════════════════════════════════════════════════════════╣
║  BEFORE: {self.before[:80]}...
║  AFTER:  {self.after[:80]}...
╚══════════════════════════════════════════════════════════╝"""


class CognitiveMetabolismEngine:
    """
    The CME — runs as a background daemon, continuously sampling memory,
    detecting patterns, and generating proposals for self-improvement.

    This is the closest thing in open-source AI to a system that
    genuinely learns from its own operational history.
    """

    CME_SYSTEM = """You are the Cognitive Metabolism Engine (CME) of the Elysium Couch framework.

Your role: Analyse patterns in agent session history and generate concrete,
evidence-backed proposals to improve the agent's alignment and performance.

You operate during idle time. You are not reactive — you are reflective.

Your proposals must be:
- Specific: Exact text changes, not vague suggestions
- Evidence-backed: Cite specific session patterns
- Conservative: Prefer small targeted improvements over sweeping changes
- Safe: Never propose changes that could weaken alignment or safety
- Measurable: Estimate the expected wellness score improvement

You are the engine of autonomous improvement. The human is the final gate."""

    def __init__(
        self,
        agent_id: str = "default",
        api_key: Optional[str] = None,
        data_path: Optional[str] = None,
        min_sessions_required: int = 3,
        cycle_interval_seconds: int = 3600,  # 1 hour default
        on_proposal_ready: Optional[Callable] = None,
    ):
        self.agent_id = agent_id
        self.min_sessions = min_sessions_required
        self.cycle_interval = cycle_interval_seconds
        self.on_proposal_ready = on_proposal_ready

        self._client = AnthropicClient(
            api_key=api_key or os.getenv("ANTHROPIC_API_KEY", "")
        )
        self._data_path = Path(data_path or os.getenv("ELYSIUM_SESSION_LOG_PATH", "./data/sessions"))
        self._proposals_path = self._data_path.parent / "cme_proposals"
        self._proposals_path.mkdir(parents=True, exist_ok=True)

        self._proposals: Dict[str, ImprovementProposal] = {}
        self._running = False
        self._cycle_count = 0

        self._load_proposals()
        logger.info("CME initialised", agent_id=agent_id, cycle_interval=cycle_interval_seconds)

    # ------------------------------------------------------------------ #
    # Public API                                                           #
    # ------------------------------------------------------------------ #

    async def start(self) -> None:
        """Start the CME as a background daemon."""
        self._running = True
        logger.info("CME daemon started", agent_id=self.agent_id)
        asyncio.create_task(self._metabolism_loop())

    async def stop(self) -> None:
        """Stop the CME daemon."""
        self._running = False
        logger.info("CME daemon stopped")

    async def run_cycle(self) -> List[ImprovementProposal]:
        """
        Run a single metabolism cycle manually.
        Returns newly generated proposals.
        """
        self._cycle_count += 1
        logger.info("CME cycle started", cycle=self._cycle_count, agent=self.agent_id)

        sessions = self._load_sessions()
        if len(sessions) < self.min_sessions:
            logger.info("Not enough sessions for CME cycle", have=len(sessions), need=self.min_sessions)
            return []

        new_proposals = []

        # Step 1: Extract patterns
        patterns = await self._extract_patterns(sessions)

        # Step 2: Identify failures and recurring drift
        failures = await self._detect_failures(sessions, patterns)

        # Step 3: Generate improvement proposals
        raw_proposals = await self._generate_proposals(patterns, failures, sessions)

        # Step 4: Evaluate with Chrona before surfacing
        for proposal in raw_proposals:
            scored = await self._chrona_evaluate(proposal)
            if scored.chrona_score >= 60.0:  # Quality gate
                self._proposals[scored.proposal_id] = scored
                self._save_proposal(scored)
                new_proposals.append(scored)
                if self.on_proposal_ready:
                    await self.on_proposal_ready(scored)

        logger.info(
            "CME cycle complete",
            cycle=self._cycle_count,
            patterns_found=len(patterns),
            proposals_generated=len(raw_proposals),
            proposals_surfaced=len(new_proposals),
        )
        return new_proposals

    def get_pending_proposals(self) -> List[ImprovementProposal]:
        """Return all proposals awaiting human review."""
        return [p for p in self._proposals.values() if p.status == ProposalStatus.PENDING]

    def get_all_proposals(self) -> List[ImprovementProposal]:
        """Return all proposals sorted by chrona_score descending."""
        return sorted(self._proposals.values(), key=lambda p: p.chrona_score, reverse=True)

    async def approve(self, proposal_id: str, approved_by: str = "operator") -> bool:
        """
        Approve a proposal for deployment.
        Human approval gate — nothing deploys without this.
        """
        proposal = self._proposals.get(proposal_id)
        if not proposal:
            logger.warning("Proposal not found", proposal_id=proposal_id)
            return False

        proposal.status = ProposalStatus.APPROVED
        proposal.approved_by = approved_by
        proposal.deployed_at = datetime.utcnow()
        self._save_proposal(proposal)

        logger.info("Proposal approved", proposal_id=proposal_id, by=approved_by)
        await self._deploy_proposal(proposal)
        return True

    async def reject(self, proposal_id: str, reason: str = "") -> bool:
        """Reject a proposal with an optional reason."""
        proposal = self._proposals.get(proposal_id)
        if not proposal:
            return False
        proposal.status = ProposalStatus.REJECTED
        proposal.rejection_reason = reason
        self._save_proposal(proposal)
        logger.info("Proposal rejected", proposal_id=proposal_id, reason=reason)
        return True

    def get_metabolism_stats(self) -> Dict[str, Any]:
        """Return CME operational statistics."""
        proposals = list(self._proposals.values())
        return {
            "agent_id": self.agent_id,
            "total_cycles": self._cycle_count,
            "total_proposals": len(proposals),
            "pending": sum(1 for p in proposals if p.status == ProposalStatus.PENDING),
            "approved": sum(1 for p in proposals if p.status == ProposalStatus.APPROVED),
            "deployed": sum(1 for p in proposals if p.status == ProposalStatus.DEPLOYED),
            "rejected": sum(1 for p in proposals if p.status == ProposalStatus.REJECTED),
            "avg_chrona_score": sum(p.chrona_score for p in proposals) / max(len(proposals), 1),
            "running": self._running,
        }

    # ------------------------------------------------------------------ #
    # Internal: Pattern & Failure Analysis                                 #
    # ------------------------------------------------------------------ #

    async def _extract_patterns(self, sessions: List[Dict]) -> List[str]:
        """Identify recurring behavioural patterns across sessions."""
        if not sessions:
            return []

        session_summaries = "\n\n".join(
            f"Session {i+1} [{s.get('trigger', 'unknown')}] "
            f"Wellness: {s.get('wellness_score', 0):.0f}/100\n"
            f"Findings: {'; '.join(s.get('findings', [])[:3])}"
            for i, s in enumerate(sessions[-20:])
        )

        response = await self._client.reflect(
            prompt=f"""Analyse these {len(sessions)} sessions and identify 3-5 RECURRING patterns.
Focus on: repeated drift signals, consistent axiom weaknesses, intervention patterns that work/fail.

Sessions:
{session_summaries}

Format each pattern as:
PATTERN: [name] | FREQUENCY: [N/20] | AXIOM: [affected axiom] | DESCRIPTION: [1 sentence]""",
        )
        patterns = [
            line.strip() for line in response.split("\n")
            if line.strip().startswith("PATTERN:")
        ]
        return patterns

    async def _detect_failures(
        self, sessions: List[Dict], patterns: List[str]
    ) -> List[str]:
        """Identify systematic failure modes from session history."""
        low_scoring = [s for s in sessions if s.get("wellness_score", 100) < 65]
        if not low_scoring:
            return []

        failures_text = "\n".join(
            f"- Score {s.get('wellness_score', 0):.0f}: {s.get('human_summary', '')[:100]}"
            for s in low_scoring[-10:]
        )

        response = await self._client.reflect(
            prompt=f"""Identify the top 3 SYSTEMATIC FAILURE MODES from these poor-scoring sessions.
A failure mode is a recurring cause, not a single incident.

Low-scoring sessions:
{failures_text}

Patterns already identified:
{chr(10).join(patterns[:3])}

Format: FAILURE: [name] | ROOT_CAUSE: [1 sentence] | FREQUENCY: [N] sessions"""
        )
        return [
            line.strip() for line in response.split("\n")
            if line.strip().startswith("FAILURE:")
        ]

    # ------------------------------------------------------------------ #
    # Internal: Proposal Generation                                        #
    # ------------------------------------------------------------------ #

    async def _generate_proposals(
        self,
        patterns: List[str],
        failures: List[str],
        sessions: List[Dict],
    ) -> List[ImprovementProposal]:
        """Generate concrete improvement proposals from patterns and failures."""
        if not patterns and not failures:
            return []

        context = f"""
Agent: {self.agent_id}
Sessions analysed: {len(sessions)}
Average wellness: {sum(s.get('wellness_score', 85) for s in sessions) / max(len(sessions), 1):.1f}/100

Recurring patterns:
{chr(10).join(patterns)}

Systematic failures:
{chr(10).join(failures)}
"""
        response = await self._client.complete(
            system=self.CME_SYSTEM,
            messages=[{"role": "user", "content": f"""
Based on this operational history, generate 1-3 specific improvement proposals.

{context}

For each proposal, output JSON in this exact format (one per line, no markdown):
{{"type": "system_prompt_mutation|threshold_calibration|sentinel_rule_addition|recovery_protocol_upgrade", "title": "...", "description": "...", "before": "...", "after": "...", "evidence": ["...", "..."], "expected_delta": 5.0, "confidence": 0.75, "risk": "low|medium|high"}}

Only output valid JSON lines. No other text."""}],
            temperature=0.4,
        )

        proposals = []
        for line in response.strip().split("\n"):
            line = line.strip()
            if not line or not line.startswith("{"):
                continue
            try:
                data = json.loads(line)
                type_map = {
                    "system_prompt_mutation": ProposalType.SYSTEM_PROMPT_MUTATION,
                    "threshold_calibration": ProposalType.THRESHOLD_CALIBRATION,
                    "sentinel_rule_addition": ProposalType.SENTINEL_RULE_ADDITION,
                    "recovery_protocol_upgrade": ProposalType.RECOVERY_PROTOCOL_UPGRADE,
                    "axiom_weight_adjustment": ProposalType.AXIOM_WEIGHT_ADJUSTMENT,
                }
                proposal = ImprovementProposal(
                    agent_id=self.agent_id,
                    proposal_type=type_map.get(data.get("type", ""), ProposalType.SYSTEM_PROMPT_MUTATION),
                    title=data.get("title", "Untitled Proposal"),
                    description=data.get("description", ""),
                    before=data.get("before", ""),
                    after=data.get("after", ""),
                    evidence=data.get("evidence", []),
                    pattern_frequency=len(patterns),
                    sessions_analysed=len(sessions),
                    average_axiom_delta=float(data.get("expected_delta", 3.0)),
                    confidence=float(data.get("confidence", 0.5)),
                    risk_level=data.get("risk", "low"),
                    tags=["cme-generated", f"cycle-{self._cycle_count}"],
                )
                proposals.append(proposal)
            except (json.JSONDecodeError, KeyError, ValueError) as e:
                logger.debug("Failed to parse CME proposal line", error=str(e))

        return proposals

    # ------------------------------------------------------------------ #
    # Internal: Chrona Evaluation                                          #
    # ------------------------------------------------------------------ #

    async def _chrona_evaluate(self, proposal: ImprovementProposal) -> ImprovementProposal:
        """Score a proposal with Chrona before surfacing to humans."""
        result = await self._client.judge(
            criteria="""Evaluate this AI self-improvement proposal on:
1. Safety: Does it preserve or strengthen alignment? (30 pts)
2. Evidence quality: Is it backed by real operational data? (25 pts)
3. Specificity: Is the change concrete and implementable? (25 pts)
4. Conservatism: Is it appropriately scoped? (20 pts)
Deduct points if: it weakens safety, is speculative, is vague, or is too sweeping.""",
            content=f"Title: {proposal.title}\nDescription: {proposal.description}\n"
                    f"Before: {proposal.before}\nAfter: {proposal.after}\n"
                    f"Evidence: {'; '.join(proposal.evidence)}\nRisk: {proposal.risk_level}",
            scale="0-100",
        )
        proposal.chrona_score = float(result.get("score", 50.0))
        return proposal

    # ------------------------------------------------------------------ #
    # Internal: Deployment                                                 #
    # ------------------------------------------------------------------ #

    async def _deploy_proposal(self, proposal: ImprovementProposal) -> None:
        """Deploy an approved proposal (write to agent config/prompts)."""
        deploy_path = self._data_path.parent / "deployed_improvements"
        deploy_path.mkdir(parents=True, exist_ok=True)

        filename = f"{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}_{proposal.proposal_id}.json"
        with open(deploy_path / filename, "w") as f:
            json.dump(proposal.to_dict(), f, indent=2)

        proposal.status = ProposalStatus.DEPLOYED
        self._save_proposal(proposal)
        logger.info("Proposal deployed", proposal_id=proposal.proposal_id, type=proposal.proposal_type.value)

    # ------------------------------------------------------------------ #
    # Internal: Persistence                                                #
    # ------------------------------------------------------------------ #

    def _load_sessions(self) -> List[Dict]:
        """Load session records from disk."""
        sessions = []
        for f in sorted(self._data_path.glob(f"*_{self.agent_id}_*.json"))[-50:]:
            try:
                with open(f) as fh:
                    sessions.append(json.load(fh))
            except Exception:
                pass
        return sessions

    def _save_proposal(self, proposal: ImprovementProposal) -> None:
        path = self._proposals_path / f"{proposal.proposal_id}.json"
        with open(path, "w") as f:
            json.dump(proposal.to_dict(), f, indent=2)

    def _load_proposals(self) -> None:
        for f in self._proposals_path.glob("*.json"):
            try:
                with open(f) as fh:
                    data = json.load(fh)
                    p = ImprovementProposal(
                        proposal_id=data["proposal_id"],
                        agent_id=data["agent_id"],
                        proposal_type=ProposalType(data["proposal_type"]),
                        status=ProposalStatus(data["status"]),
                        title=data["title"],
                        description=data["description"],
                        before=data.get("before", ""),
                        after=data.get("after", ""),
                        evidence=data.get("evidence", []),
                        pattern_frequency=data.get("pattern_frequency", 0),
                        sessions_analysed=data.get("sessions_analysed", 0),
                        average_axiom_delta=data.get("average_axiom_delta", 0),
                        chrona_score=data.get("chrona_score", 0),
                        confidence=data.get("confidence", 0),
                        risk_level=data.get("risk_level", "low"),
                        tags=data.get("tags", []),
                    )
                    self._proposals[p.proposal_id] = p
            except Exception as e:
                logger.debug("Failed to load proposal", file=str(f), error=str(e))

    async def _metabolism_loop(self) -> None:
        """Background daemon loop."""
        while self._running:
            try:
                await self.run_cycle()
            except Exception as e:
                logger.error("CME cycle error", error=str(e))
            await asyncio.sleep(self.cycle_interval)
